#write a playbook to create a file in all host nodes
- hosts: all
  tasks:
    - name: Create file in all host nodes
      file:                                 #file module we are using
        path: /home/ansible/hello.txt       #create file inside the home directory of ansible user
        state: touch                        #by using touch command
